name: code-quality-and-tests

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install pytest pytest-cov black pylint flake8 autopep8

    

    - name: Run Pylint for code quality
      run: |
        pylint src/ tests/ || true

    - name: Run Flake8 for style guide enforcement
      run: |
        flake8 src/ tests/ || true

    - name: Check autopep8 diff
      run: |
        autopep8 --diff --recursive .
    
    # - name: Check code formatting with Black
    #   run: |
    #     black --check src/ tests/


    - name: Run pytest with coverage
      run: |
        pytest tests --cov=. --cov-report=term-missing
