name: Frames

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/run_pytest_with_coverage.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/run_pytest_with_coverage.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt
        pip install pytest pytest-cov black pylint
      

    - name: Format code with Black
      run: |
        black src/ tests/
    
    - name: Check code formatting with Black
      run: |
        black --check src/ tests/

    - name: Run Pylint for code quality
      run: |
        pylint src/ tests/ || true
    
    - name: Run pytest with coverage
      run: |
        pytest tests --cov=app --cov-report=term-missing