name: Frames

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/run_pytest_with_coverage.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/run_pytest_with_coverage.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Adjust if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -r src/requirements.txt  # Remove this if no requirements file

    - name: Run pytest with coverage
      run: |
        pytest --cov=. --cov-report=term-missing

    # Optional: Enforce minimum coverage (uncomment below to use)
    # - name: Run pytest with coverage threshold
    #   run: |
    #     cd app
    #     pytest --cov=. --cov-fail-under=80  # Fails if coverage < 80%
