name: Frames

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/run_pytest_with_coverage.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/run_pytest_with_coverage.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov black
        pip install -r src/requirements.txt  # Remove this if no requirements file

    - name: Check code formatting with Black
      run: |
        black --check src/ tests/

    - name: Run pytest with coverage
      run: |
        pytest 

    # Optional: Enforce minimum coverage (uncomment below to use)
    # - name: Run pytest with coverage threshold
    #   run: |
    #     cd app
    #     pytest --cov=. --cov-fail-under=80
