name: Run Pytest Tests

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/run_pytest.yml'
  pull_request:
    paths:
      - 'src/**'
      - '.github/workflows/run_pytest.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # or your preferred version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r src/requirements.txt  # if your app folder has requirements

    - name: Run pytest
      run: |
        pytest
